version: '3.7'
services:

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    image: spring-boot-image
    build: backend
    ports:
      - 8088:8088
    volumes:
      - $HOME/.m2/repository:/root/.m2/repository
      - /data/backend